# Generated by Django 5.0.2 on 2024-02-28 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Edycja',
                'verbose_name_plural': 'Edycje',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('win_points', models.SmallIntegerField()),
                ('draw_points', models.SmallIntegerField()),
                ('lose_points', models.SmallIntegerField()),
                ('archive', models.BooleanField(default=False)),
                ('emoji', models.CharField(default='🏆', max_length=2)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sporty',
            },
        ),
        migrations.CreateModel(
            name='GlobalRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.SmallIntegerField()),
                ('total_points', models.SmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.department')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.edition')),
            ],
        ),
        migrations.CreateModel(
            name='SportGlobalPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_place_points', models.SmallIntegerField()),
                ('second_place_points', models.SmallIntegerField(default=0)),
                ('third_place_points', models.SmallIntegerField(default=0)),
                ('fourth_place_points', models.SmallIntegerField(default=0)),
                ('other_places_points', models.SmallIntegerField(default=0)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.edition')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.sport')),
            ],
            options={
                'verbose_name': 'Punkty globalne',
                'verbose_name_plural': 'Punkty globalne',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.SmallIntegerField()),
                ('total_points', models.SmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.department')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.edition')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('score_team_one', models.SmallIntegerField()),
                ('score_team_two', models.SmallIntegerField()),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_one', to='ligapwr.team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_two', to='ligapwr.team')),
                ('winner_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner_team', to='ligapwr.team')),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_capitan', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
