# Generated by Django 5.0 on 2024-03-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.SmallIntegerField()),
                ('total_points', models.SmallIntegerField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.edition')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.sport')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ligapwr.team')),
            ],
        ),
    ]
