# Generated by Django 5.0 on 2024-03-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0002_sportranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportranking',
            name='place_for_department',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
