# Generated by Django 5.0.2 on 2024-03-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0002_sportranking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Wydzial', 'verbose_name_plural': 'Wydzialy'},
        ),
        migrations.AlterModelOptions(
            name='globalranking',
            options={'verbose_name': 'Ranking globalny', 'verbose_name_plural': 'Ranking Globalny'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Mecz', 'verbose_name_plural': 'Mecze'},
        ),
        migrations.AlterModelOptions(
            name='sportranking',
            options={'verbose_name': 'Raking sportu', 'verbose_name_plural': 'Ranking sportu'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Druzyna', 'verbose_name_plural': 'Druzyny'},
        ),
        migrations.AlterModelOptions(
            name='userteam',
            options={'verbose_name': 'Zawodnik', 'verbose_name_plural': 'Zawodnicy'},
        ),
    ]
