# Generated by Django 5.0.2 on 2024-03-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0003_alter_department_options_alter_globalranking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_team_one',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team_two',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner_team', to='ligapwr.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='place',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_points',
            field=models.SmallIntegerField(null=True),
        ),
    ]
