# Generated by Django 5.0 on 2024-03-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0003_sportranking_place_for_department'),
        ('ligapwr', '0004_alter_match_score_team_one_and_more'),
    ]

    operations = [
    ]
