# Generated by Django 5.0 on 2024-03-10 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0005_merge_20240310_1952'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Wydział', 'verbose_name_plural': 'Wydziały'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Drużyna', 'verbose_name_plural': 'Drużyny'},
        ),
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
