# Generated by Django 5.0 on 2024-03-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0009_sportranking_draws_sportranking_loses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportranking',
            name='draws',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sportranking',
            name='loses',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sportranking',
            name='maches',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sportranking',
            name='wins',
            field=models.SmallIntegerField(default=0),
        ),
    ]
