# Generated by Django 5.0 on 2024-03-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0010_alter_sportranking_draws_alter_sportranking_loses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_team_one',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_team_two',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
