# Generated by Django 5.0.3 on 2024-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0011_alter_match_score_team_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='emoji',
            field=models.CharField(default='🏆', max_length=2),
        ),
    ]
