# Generated by Django 5.0.3 on 2024-04-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0013_player_team_players'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Zawodnik', 'verbose_name_plural': 'Zawodnicy'},
        ),
        migrations.AlterModelOptions(
            name='userteam',
            options={'verbose_name': 'Kapitan', 'verbose_name_plural': 'Kapitanowie'},
        ),
    ]
