# Generated by Django 5.0.3 on 2024-04-24 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligapwr', '0015_team_capitan_delete_userteam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalranking',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligapwr.department'),
        ),
        migrations.AlterField(
            model_name='globalranking',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligapwr.edition'),
        ),
        migrations.AlterField(
            model_name='sportglobalpoints',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligapwr.edition'),
        ),
        migrations.AlterField(
            model_name='sportglobalpoints',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligapwr.sport'),
        ),
        migrations.AlterField(
            model_name='sportranking',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligapwr.edition'),
        ),
        migrations.AlterField(
            model_name='sportranking',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligapwr.sport'),
        ),
        migrations.AlterField(
            model_name='sportranking',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligapwr.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='capitan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, to='ligapwr.player'),
        ),
    ]
